#!/usr/bin/env bash
# display information about subdomains configured on te DNS management website
information () {
    dig "$1" | grep -A1 'ANSWER SECTION:' | sed -r "s/$1./$2/g" | awk -F" " 'NR==2 { print "The subdomain " $1 " is a " $4 " record and points to " $5 }'
}

if [ "$#" -eq 2 ]
then
    information "$2.$1" "$2"
else
    subdomains=("www" "lb-01" "web-01" "web-02")
    for sub in "${subdomains[@]}"
    do
        information "$sub.$1" "$sub"
    done
fi
