#!/usr/bin/env bash
# Configure Nginx so that its HTTP response contains a custom header (on web-01 and web-02)
sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo sed -i '/http {/a \    add_header X-Served-By $HOSTNAME;' /etc/nginx/nginx.conf
echo "Hello World!" | sudo tee /var/www/html/index.html
echo "Ceci n'est pas une page" | sudo tee /var/www/html/error_404.html
sudo sed -i '37i\ rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
sudo sed -i '38i\ error_page 404 /error_404.html;' /etc/nginx/sites-available/default
sudo service nginx restart
