#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server
# Configure HAproxy so that it send traffic to web-01 and web-02
# Make sure that HAproxy can be managed via an init script

sudo apt-get -y update
sudo apt-get install -y haproxy

balancer="\
frontend haproxy_balancer
	 bind *:80
	 default_backend webservers

backend webservers
   	balance roundrobin
   	server 1615-web-01 3.85.196.66:80 check
	server 1615-web-02 54.175.225.232:80 check
"
echo "$balancer" sudo tee -a /etc/haproxy/haproxy.cfg

sudo service haproxy start
