#!/usr/bin/env bash
# displays To infinity and beyond indefinitely
# display I am invincible!!! when receiving a SIGTERM signal

while true;
do
    echo "To infinity and beyond"
    sleep 2
    trap 'echo "I am invicible!!!"' SIGTERM
done
