#!/usr/bin/env bash
# displays the content of the current directory in a list format
# Where only the part of the name after the first dash is displayed

List=$(ls)
for i in $List; do
    echo "$i" | cut -d '-' -f2
done
